AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Allow TICF analysts to view the results of Athena queries on TxMA audit data

Parameters:
  CodeSigningConfigArn:
    Description: The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Type: String
    Default: none
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  PermissionsBoundary:
    Description: The ARN of the permissions boundary to apply to any role created by the template
    Type: String
    Default: none
  TestRoleArn:
    Type: String
    Description: The ARN of the role that will used for integration tests
    Default: none

Conditions:
  ApiCustomDomain: !Not [!Equals [!Ref Environment, dev]]
  TestEnvironment:
    !Not [
      !Or [
        !Equals [!Ref Environment, production],
        !Equals [!Ref Environment, integration]
      ]
    ]
  UseCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, none]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]
  TestRolePolicy: !Not [!Equals [!Ref TestRoleArn, none]]
  IsStubbedEnvironment:
    !Or [!Equals [!Ref Environment, dev], !Equals [!Ref Environment, build]]
  TestRoleResources:
    !And [Condition: TestEnvironment, !Not [!Equals [!Ref TestRoleArn, none]]]

Globals:
  Function:
    CodeSigningConfigArn:
      !If [UseCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]
    CodeUri: dist/
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    ReservedConcurrentExecutions: 10
    Runtime: nodejs16.x
    Timeout: 15
  Api:
    OpenApiVersion: 3.0.1

Resources:
  ResultsApi:
    #checkov:skip=CKV_AWS_120:We explicitly don't want caching
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ResultsApiAccessLogs.Arn
        Format: >-
          {
          "requestId": "$context.requestId",
          "ip": "$context.identity.sourceIp",
          "requestTime": "$context.requestTime",
          "httpMethod": "$context.httpMethod",
          "path": "$context.path",
          "routeKey": "$context.routeKey",
          "status": "$context.status",
          "protocol": "$context.protocol",
          "responseLatency": "$context.responseLatency",
          "responseLength": "$context.responseLength"
          }
      Description: API used by TICF analysts to access the results of Athena queries on the raw audit data
      DisableExecuteApiEndpoint: !If [ApiCustomDomain, true, false]
      EndpointConfiguration:
        Type: REGIONAL
      GatewayResponses:
        ACCESS_DENIED:
          ResponseTemplates:
            application/json: '{"message": "Access Denied: if you think you should have access to this URL, make sure you are connected to the VPN"}'
      Name: !Sub ${AWS::StackName}-secure-fraud-site-api
      StageName: !Ref Environment
      TracingEnabled: true

  ResultsApiBasePathMapping:
    Condition: ApiCustomDomain
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: '{{resolve:ssm:ResultsApiDomainName}}'
      RestApiId: !Ref ResultsApi
      Stage: !Ref ResultsApi.Stage

  ResultsApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId: '{{resolve:ssm:LogsKmsKeyArn}}'
      LogGroupName: !Sub /aws/apigateway/${ResultsApi}-access-logs
      RetentionInDays: 30

  SecureFraudApiWafAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}::/restapis/${ResultsApi}/stages/${ResultsApi.Stage}
      WebACLArn: '{{resolve:ssm:SecureFraudApiWafAclArn}}'

  ConfirmDownloadFunction:
    #checkov:skip=CKV_AWS_115:Defined in Globals
    #checkov:skip=CKV_AWS_116:Lambda is behind an API gateway, so repeated processing of the same message isn't a problem
    #checkov:skip=CKV_AWS_117:VPC not required
    Type: AWS::Serverless::Function
    Properties:
      Handler: confirmDownload.handler
      Environment:
        Variables:
          SECURE_DOWNLOAD_TABLE_NAME: '{{resolve:ssm:SecureFraudSiteDataTableName}}'
          LINK_EXPIRY_TIME: '{{resolve:ssm:LINK_EXPIRY_TIME}}'
          AUDIT_DATA_REQUEST_EVENTS_QUEUE_URL: '{{resolve:ssm:AuditDataRequestEventsQueueUrl}}'
      FunctionName: !Sub ${AWS::StackName}-confirm-download-page
      KmsKeyArn: '{{resolve:ssm:LambdaKmsKeyArn}}'
      Events:
        ConfirmDownload:
          Type: Api
          Properties:
            RestApiId: !Ref ResultsApi
            Method: post
            Path: /secure/{downloadHash}
      Policies:
        - Statement:
            - Sid: SecureFraudSiteDataTableReadWrite
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: '{{resolve:ssm:SecureFraudSiteDataTableArn}}'
            - Sid: DecryptKmsKeys
              Effect: Allow
              Action:
                - kms:Decrypt
              Resource: '{{resolve:ssm:DatabaseKmsKeyArn}}'
            - Sid: S3ResultsBucketRead
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: '{{resolve:ssm:QueryResultsBucketArn}}/*'
            - Sid: Logs
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !GetAtt ConfirmDownloadFunctionLogs.Arn
            - Sid: AllowSqsAuditEventsSend
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: '{{resolve:ssm:AuditDataRequestEventsQueueArn}}'
            - Sid: AllowQueueKmsKeyAccess
              Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:ReEncrypt*
              Resource: '{{resolve:ssm:AuditDataRequestEventsQueueKmsKeyArn}}'

  ConfirmDownloadFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId: '{{resolve:ssm:LogsKmsKeyArn}}'
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-confirm-download-page'
      RetentionInDays: 30

  DownloadWarningFunction:
    #checkov:skip=CKV_AWS_115:Defined in Globals
    #checkov:skip=CKV_AWS_116:Lambda is behind an API gateway, so repeated processing of the same message isn't a problem
    #checkov:skip=CKV_AWS_117:VPC not required
    Type: AWS::Serverless::Function
    Properties:
      Handler: downloadWarning.handler
      Environment:
        Variables:
          SECURE_DOWNLOAD_TABLE_NAME: '{{resolve:ssm:SecureFraudSiteDataTableName}}'
          LINK_EXPIRY_TIME: '{{resolve:ssm:LINK_EXPIRY_TIME}}'
      Events:
        DownloadWarning:
          Type: Api
          Properties:
            RestApiId: !Ref ResultsApi
            Method: get
            Path: /secure/{downloadHash}
      FunctionName: !Sub ${AWS::StackName}-download-warning-page
      KmsKeyArn: '{{resolve:ssm:LambdaKmsKeyArn}}'
      Policies:
        - Statement:
            - Sid: SecureFraudSiteDataTableRead
              Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: '{{resolve:ssm:SecureFraudSiteDataTableArn}}'
            - Sid: DecryptDatabaseKmsKey
              Effect: Allow
              Action:
                - kms:Decrypt
              Resource: '{{resolve:ssm:DatabaseKmsKeyArn}}'
            - Sid: Logs
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !GetAtt DownloadWarningFunctionLogs.Arn

  DownloadWarningFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId: '{{resolve:ssm:LogsKmsKeyArn}}'
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-download-warning-page'
      RetentionInDays: 30

  SendEmailRequestToNotifyFunction:
    #checkov:skip=CKV_AWS_115:Defined in Globals section
    #checkov:skip=CKV_AWS_116:Unsure of what will call the function currently - need revision at a later point
    #checkov:skip=CKV_AWS_117:VPC not required
    Type: AWS::Serverless::Function
    Properties:
      Handler: sendEmailRequestToNotify.handler
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          NOTIFY_API_SECRETS_ARN: '{{resolve:ssm:NotifySecretSetArn}}'
          CLOSE_TICKET_QUEUE_URL: '{{resolve:ssm:CloseZendeskTicketQueueUrl}}'
          USE_NOTIFY_MOCK_SERVER: !If [IsStubbedEnvironment, 'true', 'false']
          MOCK_SERVER_BASE_URL: 'https://mockserver.transaction.build.account.gov.uk'
      FunctionName: !Sub ${AWS::StackName}-send-email-request-to-notify
      KmsKeyArn: '{{resolve:ssm:LambdaKmsKeyArn}}'
      Events:
        SendEmailEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SendEmailQueue.Arn
            BatchSize: 1
      Policies:
        - Statement:
            - Sid: Logs
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !GetAtt SendEmailRequestToNotifyLogs.Arn
            - Sid: ReadSecrets
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - '{{resolve:ssm:NotifySecretSetArn}}'
            - Sid: AllowCloseTicketQueueSend
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: '{{resolve:ssm:CloseZendeskTicketQueueArn}}'
            - Sid: UseSqsKmsKey
              Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:ReEncrypt*
              Resource:
                - '{{resolve:ssm:CloseZendeskTicketQueueKmsKeyArn}}'
            - Sid: DecryptKmsKeys
              Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - '{{resolve:ssm:SecretsKmsKeyArn}}'
                - '{{resolve:ssm:SqsKmsKeyArn}}'

  SendEmailRequestToNotifyLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId: '{{resolve:ssm:LogsKmsKeyArn}}'
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-send-email-request-to-notify'
      RetentionInDays: 30

  SendEmailQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-${Environment}-send-email-queue
      KmsMasterKeyId: '{{resolve:ssm:SqsKmsKeyArn}}'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SendEmailDeadLetterQueue.Arn
        maxReceiveCount: 5

  SendEmailDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-${Environment}-send-email-dead-letter-queue
      KmsMasterKeyId: '{{resolve:ssm:SqsKmsKeyArn}}'

  GenerateDownloadFunction:
    #checkov:skip=CKV_AWS_117:VPC not required
    #checkov:skip=CKV_AWS_115:Defined in Globals section
    #checkov:skip=CKV_AWS_116:Queue we read from has DLQ set up
    Type: AWS::Serverless::Function
    Properties:
      Handler: generateDownload.handler
      Role: !GetAtt GenerateDownloadFunctionRole.Arn
      Environment:
        Variables:
          ATHENA_OUTPUT_BUCKET_NAME: !Sub txma-data-analysis-${Environment}-athena-query-output-bucket
          QUERY_RESULTS_BUCKET_NAME: '{{resolve:ssm:QueryResultsBucketName}}'
          SECURE_DOWNLOAD_LINK_BASE_URL:
            !If [
              ApiCustomDomain,
              'https://{{resolve:ssm:ResultsApiDomainName}}/secure',
              !Sub 'https://${ResultsApi}.execute-api.${AWS::Region}.amazonaws.com/${ResultsApi.Stage}/secure'
            ]
          SECURE_DOWNLOAD_TABLE_NAME: '{{resolve:ssm:SecureFraudSiteDataTableName}}'
          SEND_TO_EMAIL_QUEUE_URL: !Ref SendEmailQueue
          DATABASE_TTL_HOURS: '{{resolve:ssm:DatabaseTtlHours}}'
      Events:
        QueryCompleteEvent:
          Type: SQS
          Properties:
            Queue: !Sub 'arn:aws:sqs:${AWS::Region}:{{resolve:ssm:AuditAccountNumber}}:txma-data-analysis-${Environment}-query-completed-queue'
            BatchSize: 1
      FunctionName: !Sub ${AWS::StackName}-generate-download
      KmsKeyArn: '{{resolve:ssm:LambdaKmsKeyArn}}'

  GenerateDownloadFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      KmsKeyId: '{{resolve:ssm:LogsKmsKeyArn}}'
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-generate-download'
      RetentionInDays: 30

  GenerateDownloadFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-${Environment}-generate-download-role
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue
        ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowGenerateDownloadActions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: SecureFraudSiteDataTableWrite
                Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: '{{resolve:ssm:SecureFraudSiteDataTableArn}}'
              - Sid: DecryptDatabaseKmsKey
                Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: '{{resolve:ssm:DatabaseKmsKeyArn}}'
              - Sid: Logs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt GenerateDownloadFunctionLogs.Arn
              - Sid: AllowQueryCompletedQueueRead
                Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub 'arn:aws:sqs:${AWS::Region}:{{resolve:ssm:AuditAccountNumber}}:txma-data-analysis-${Environment}-query-completed-queue'
              - Sid: AllowAccessAthenaOutputBucket
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::txma-data-analysis-${Environment}-athena-query-output-bucket/*'
              - Sid: AllowDecryptOfAuditAccountKmsKeys
                Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub 'arn:aws:kms:${AWS::Region}:{{resolve:ssm:AuditAccountNumber}}:*'
              - Sid: S3ResultsBucketWrite
                Effect: Allow
                Action:
                  - s3:PutObject
                Resource: '{{resolve:ssm:QueryResultsBucketArn}}/*'
              - Sid: AllowSqsSendToEmailQueue
                Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - !GetAtt SendEmailQueue.Arn
              - Sid: UseSQSKmsKeyForSendToEmailQueue
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: '{{resolve:ssm:SqsKmsKeyArn}}'

  # Query results integration test resources
  IntegrationTestsSqsOperationsFunctionNameParameter:
    Condition: TestEnvironment
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /tests/${AWS::StackName}/SqsOperationsFunctionName
      Type: String
      Value: '{{resolve:ssm:/tests/SqsOperationsFunctionName}}'

  IntegrationTestsWriteTestDataToAthenaBucketQueueUrlParameter:
    Condition: TestEnvironment
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /tests/${AWS::StackName}/WriteTestDataToAthenaBucketQueueUrl
      Type: String
      Value: '{{resolve:ssm:/tests/WriteTestDataToAthenaBucketQueueUrl}}'

  IntegrationTestsNotifySecretSet:
    Condition: TestEnvironment
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub tests/${AWS::StackName}/NotifySecrets
      KmsKeyId: '{{resolve:ssm:SecretsKmsKeyArn}}'

  IntegrationTestsSecureDownloadWebsiteBaseUrlParameter:
    Condition: TestEnvironment
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /tests/${AWS::StackName}/SecureDownloadWebsiteBaseUrl
      Type: String
      Value:
        !If [
          ApiCustomDomain,
          'https://{{resolve:ssm:ResultsApiDomainName}}/secure',
          !Sub 'https://${ResultsApi}.execute-api.${AWS::Region}.amazonaws.com/${ResultsApi.Stage}/secure'
        ]

  SqsOperationsLambdaPolicy:
    Condition: TestRoleResources
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt IntegrationTestsSqsOperationsFunctionNameParameter.Value
      Principal: !Ref TestRoleArn
