name: Delete feature branch stack

on:
  delete:
    branches-ignore:
      - main

env:
  AWS_REGION: eu-west-2

jobs:
  delete-feature:
    name: Delete feature branch
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@c71dd89d980e49367c70391e8ada4353f52f2800 # v2
      - name: Assume the dev account deployment role
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ACTIONS_DEV_DEPLOY_ROLE_ARN }}
      - name: Delete feature branch stack
        env:
          FEATURE_BRANCH_NAME: ${{ github.event.ref }}
        run: |
          stack_name=$(
            echo ${FEATURE_BRANCH_NAME##*/} | \
            tr -cd '[a-zA-Z0-9-]' | \
            tr '[:upper:]' '[:lower:]' | \
            cut -c -32
          )

          sam delete \
            --stack-name ${stack_name} \
            --region ${AWS_REGION} \
            --no-prompts
